name: pro_video_editor_example
description: "Demonstrates how to use the pro_video_editor plugin."
publish_to: 'none'

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  pro_video_editor:
    path: ../


  intl: ^0.20.1
  cupertino_icons: ^1.0.9

  pro_image_editor: ^12.4.7
  
  google_fonts: ^8.1.0
  flex_color_picker: ^3.8.0
  file_picker: 12.0.0-beta.3 #^10.2.1
  mime: ^2.0.0
  wav: 1.5.0

  path_provider: ^2.1.5
  audioplayers: ^6.7.1

  # Video
  video_player: ^2.11.1
  fvp: ^0.37.2
  chewie: ^1.14.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^6.0.0
 

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/tests/

  config:
    enable-swift-package-manager: false